"""empty message

Revision ID: 65ed938766ad
Revises: 86d66182748c
Create Date: 2025-11-25 08:09:46.708739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65ed938766ad'
down_revision: Union[str, None] = '86d66182748c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedbacks_id', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.add_column('organizations', sa.Column('cnpj', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'contact_phone')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'cnpj')
    op.create_table('feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='feedbacks_organization_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feedbacks_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feedbacks_pkey')
    )
    op.create_index('ix_feedbacks_id', 'feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###
