"""Reset total do banco

Revision ID: c52875b0d6c5
Revises: 
Create Date: 2026-03-13 14:01:14.436284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52875b0d6c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('productive_hours', sa.Float(), nullable=False),
    sa.Column('unproductive_hours', sa.Float(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('top_reasons_snapshot', sa.JSON(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_daily_metrics_date'), 'employee_daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_employee_daily_metrics_id'), 'employee_daily_metrics', ['id'], unique=False)
    op.create_table('machine_daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('running_hours', sa.Float(), nullable=False),
    sa.Column('idle_hours', sa.Float(), nullable=False),
    sa.Column('pause_hours', sa.Float(), nullable=False),
    sa.Column('maintenance_hours', sa.Float(), nullable=False),
    sa.Column('planned_stop_hours', sa.Float(), nullable=False),
    sa.Column('micro_stop_hours', sa.Float(), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('utilization', sa.Float(), nullable=False),
    sa.Column('mtbf', sa.Float(), nullable=False),
    sa.Column('mttr', sa.Float(), nullable=False),
    sa.Column('top_reasons_snapshot', sa.JSON(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_daily_metrics_date'), 'machine_daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_machine_daily_metrics_id'), 'machine_daily_metrics', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.String(length=100), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=False),
    sa.Column('scrap_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_code'), 'production_orders', ['code'], unique=True)
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('sap_resource_code', sa.String(), nullable=True),
    sa.Column('layout_x', sa.Float(), nullable=True),
    sa.Column('layout_y', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'IN_USE_AUTONOMOUS', 'SETUP', 'MAINTENANCE', 'STOPPED', name='machinestatus'), nullable=False),
    sa.Column('telemetry_device_id', sa.String(length=100), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('maintenance_notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', 'organization_id', name='_machine_identifier_org_uc'),
    sa.UniqueConstraint('identifier', 'organization_id', name='_machine_license_org_uc')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_telemetry_device_id'), 'machines', ['telemetry_device_id'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('PECA', 'FLUIDO', 'CONSUMIVEL', 'PNEU', 'FERRAMENTA', 'EPI', 'OUTRO', name='partcategory'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('invoice_url', sa.String(length=512), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('minimum_stock', sa.Integer(), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('lifespan_km', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    op.create_index(op.f('ix_parts_name'), 'parts', ['name'], unique=False)
    op.create_index(op.f('ix_parts_part_number'), 'parts', ['part_number'], unique=False)
    op.create_index(op.f('ix_parts_serial_number'), 'parts', ['serial_number'], unique=True)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('device_token', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'PCP', 'QUALITY', 'LOGISTICS', 'MAINTENANCE', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'organization_id', name='_user_employee_org_uc')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('andon_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('sector', sa.Enum('MAINTENANCE', 'QUALITY', 'PCP', 'MANAGER', 'LOGISTICS', 'SECURITY', name='andonsector'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='andonstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_andon_calls_id'), 'andon_calls', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('CNH', 'CRLV', 'ANTT', 'ASO', 'SEGURO', 'OUTRO', name='documenttype'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_identifier', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'EM_USO', 'FIM_DE_VIDA', 'EM_MANUTENCAO', name='inventoryitemstatus'), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('installed_on_machine_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['installed_on_machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'item_identifier', name='_part_item_identifier_uc')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_identifier'), 'inventory_items', ['item_identifier'], unique=False)
    op.create_index(op.f('ix_inventory_items_status'), 'inventory_items', ['status'], unique=False)
    op.create_table('machine_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cost_type', sa.Enum('MANUTENCAO', 'COMBUSTIVEL', 'PEDAGIO', 'SEGURO', 'PNEU', 'PECAS_COMPONENTES', 'MULTA', 'OUTROS', 'MANUTENCAO_CORRETIVA', 'MANUTENCAO_PREVENTIVA', 'ENERGIA_ELETRICA', 'PECAS_REPOSICAO', 'INSUMOS', 'SERVICOS_TERCEIROS', name='costtype'), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_costs_id'), 'machine_costs', ['id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'PENDENTE', 'APROVADA', 'REJEITADA', 'EM_ANDAMENTO', 'CONCLUIDA', name='maintenancestatus'), nullable=False),
    sa.Column('category', sa.Enum('MECHANICAL', 'ELECTRICAL', 'HYDRAULIC', 'PNEUMATIC', 'BODYWORK', 'OTHER', name='maintenancecategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('manager_notes', sa.Text(), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mechanical', sa.Boolean(), nullable=True),
    sa.Column('is_electrical', sa.Boolean(), nullable=True),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(), nullable=True),
    sa.Column('supervisor', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_id'), 'maintenance_requests', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notification_type', sa.Enum('MAINTENANCE_DUE_DATE', 'MAINTENANCE_DUE_KM', 'DOCUMENT_EXPIRING', 'LOW_STOCK', 'COST_EXCEEDED', 'MAINTENANCE_REQUEST_NEW', 'MAINTENANCE_REQUEST_STATUS_UPDATE', 'MAINTENANCE_REQUEST_NEW_COMMENT', name='notificationtype'), nullable=False),
    sa.Column('related_entity_type', sa.String(), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('related_machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['related_machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('production_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('operator_badge', sa.String(length=50), nullable=False),
    sa.Column('appointment_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('sap_doc_num', sa.String(length=50), nullable=True),
    sa.Column('sap_position', sa.String(length=10), nullable=True),
    sa.Column('sap_operation_code', sa.String(length=50), nullable=True),
    sa.Column('sap_operation_desc', sa.String(length=255), nullable=True),
    sa.Column('sap_service_desc', sa.String(length=255), nullable=True),
    sa.Column('sap_operator_name', sa.String(length=100), nullable=True),
    sa.Column('operator_id', sa.String(length=50), nullable=True),
    sa.Column('sap_resource_code', sa.String(length=50), nullable=True),
    sa.Column('sap_resource_name', sa.String(length=100), nullable=True),
    sa.Column('sap_data_source', sa.String(length=10), nullable=False),
    sa.Column('sap_doc_type', sa.String(length=10), nullable=False),
    sa.Column('sap_origin', sa.String(length=10), nullable=False),
    sa.Column('sap_service_code', sa.String(length=100), nullable=True),
    sa.Column('sap_stop_reason_code', sa.String(length=50), nullable=True),
    sa.Column('sap_stop_reason_desc', sa.String(length=255), nullable=True),
    sa.Column('sap_is_setup', sa.String(length=1), nullable=False),
    sa.Column('sap_stoppage_apt', sa.String(length=1), nullable=False),
    sa.Column('sap_status', sa.String(length=20), nullable=False),
    sa.Column('sap_message', sa.Text(), nullable=True),
    sa.Column('target_qty', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_appointments_id'), 'production_appointments', ['id'], unique=False)
    op.create_index(op.f('ix_production_appointments_operator_badge'), 'production_appointments', ['operator_badge'], unique=False)
    op.create_table('production_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operator_badge', sa.String(length=50), nullable=True),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_logs_id'), 'production_logs', ['id'], unique=False)
    op.create_table('production_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_produced', sa.Integer(), nullable=False),
    sa.Column('total_scrap', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('productive_seconds', sa.Integer(), nullable=False),
    sa.Column('unproductive_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_sessions_id'), 'production_sessions', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('ENTRADA', 'SAIDA_USO', 'FIM_DE_VIDA', 'AJUSTE_INICIAL', 'INSTALACAO', 'DESCARTE', 'SAIDA_REPARO', name='transactiontype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('related_machine_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['related_machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('maintenance_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_comments_id'), 'maintenance_comments', ['id'], unique=False)
    op.create_table('maintenance_service_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_service_items_id'), 'maintenance_service_items', ['id'], unique=False)
    op.create_table('production_time_slices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_productive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['production_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_time_slices_id'), 'production_time_slices', ['id'], unique=False)
    op.create_table('machine_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('inventory_transaction_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('installation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uninstallation_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_transaction_id')
    )
    op.create_index(op.f('ix_machine_components_id'), 'machine_components', ['id'], unique=False)
    op.create_table('maintenance_part_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('component_removed_id', sa.Integer(), nullable=True),
    sa.Column('component_installed_id', sa.Integer(), nullable=True),
    sa.Column('is_reverted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_installed_id'], ['machine_components.id'], ),
    sa.ForeignKeyConstraint(['component_removed_id'], ['machine_components.id'], ),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_part_changes_id'), 'maintenance_part_changes', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_part_changes_is_reverted'), 'maintenance_part_changes', ['is_reverted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_part_changes_is_reverted'), table_name='maintenance_part_changes')
    op.drop_index(op.f('ix_maintenance_part_changes_id'), table_name='maintenance_part_changes')
    op.drop_table('maintenance_part_changes')
    op.drop_index(op.f('ix_machine_components_id'), table_name='machine_components')
    op.drop_table('machine_components')
    op.drop_index(op.f('ix_production_time_slices_id'), table_name='production_time_slices')
    op.drop_table('production_time_slices')
    op.drop_index(op.f('ix_maintenance_service_items_id'), table_name='maintenance_service_items')
    op.drop_table('maintenance_service_items')
    op.drop_index(op.f('ix_maintenance_comments_id'), table_name='maintenance_comments')
    op.drop_table('maintenance_comments')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_production_sessions_id'), table_name='production_sessions')
    op.drop_table('production_sessions')
    op.drop_index(op.f('ix_production_logs_id'), table_name='production_logs')
    op.drop_table('production_logs')
    op.drop_index(op.f('ix_production_appointments_operator_badge'), table_name='production_appointments')
    op.drop_index(op.f('ix_production_appointments_id'), table_name='production_appointments')
    op.drop_table('production_appointments')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_maintenance_requests_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_machine_costs_id'), table_name='machine_costs')
    op.drop_table('machine_costs')
    op.drop_index(op.f('ix_inventory_items_status'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_identifier'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_andon_calls_id'), table_name='andon_calls')
    op.drop_table('andon_calls')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_parts_serial_number'), table_name='parts')
    op.drop_index(op.f('ix_parts_part_number'), table_name='parts')
    op.drop_index(op.f('ix_parts_name'), table_name='parts')
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_machines_telemetry_device_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_code'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_machine_daily_metrics_id'), table_name='machine_daily_metrics')
    op.drop_index(op.f('ix_machine_daily_metrics_date'), table_name='machine_daily_metrics')
    op.drop_table('machine_daily_metrics')
    op.drop_index(op.f('ix_employee_daily_metrics_id'), table_name='employee_daily_metrics')
    op.drop_index(op.f('ix_employee_daily_metrics_date'), table_name='employee_daily_metrics')
    op.drop_table('employee_daily_metrics')
    # ### end Alembic commands ###
