"""initial_sync_final

Revision ID: d450850033cf
Revises: 
Create Date: 2026-02-09 09:30:53.687678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd450850033cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('employee_daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('productive_hours', sa.Float(), nullable=True),
    sa.Column('unproductive_hours', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('top_reasons_snapshot', sa.JSON(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_daily_metrics_date'), 'employee_daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_employee_daily_metrics_id'), 'employee_daily_metrics', ['id'], unique=False)
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('polygon_points', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofences_id'), 'geofences', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('fuel_provider_name', sa.String(length=100), nullable=True),
    sa.Column('encrypted_fuel_provider_api_key', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_fuel_provider_api_secret', sa.LargeBinary(), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('vehicle_limit', sa.Integer(), nullable=False),
    sa.Column('driver_limit', sa.Integer(), nullable=False),
    sa.Column('freight_order_limit', sa.Integer(), nullable=False),
    sa.Column('maintenance_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.String(length=100), nullable=False),
    sa.Column('part_image_url', sa.String(length=255), nullable=True),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=False),
    sa.Column('scrap_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_code'), 'production_orders', ['code'], unique=True)
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_table('vehicle_daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('running_hours', sa.Float(), nullable=True),
    sa.Column('idle_hours', sa.Float(), nullable=True),
    sa.Column('maintenance_hours', sa.Float(), nullable=True),
    sa.Column('planned_stop_hours', sa.Float(), nullable=True),
    sa.Column('availability', sa.Float(), nullable=True),
    sa.Column('utilization', sa.Float(), nullable=True),
    sa.Column('top_reasons_snapshot', sa.JSON(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_daily_metrics_date'), 'vehicle_daily_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_vehicle_daily_metrics_id'), 'vehicle_daily_metrics', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='_client_name_org_uc')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('demousage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('period', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demousage_id'), 'demousage', ['id'], unique=False)
    op.create_index(op.f('ix_demousage_organization_id'), 'demousage', ['organization_id'], unique=False)
    op.create_index(op.f('ix_demousage_resource_type'), 'demousage', ['resource_type'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('implements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implements_id'), 'implements', ['id'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('PECA', 'FLUIDO', 'CONSUMIVEL', 'PNEU', 'FERRAMENTA', 'EPI', 'OUTRO', name='partcategory'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('invoice_url', sa.String(length=512), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('minimum_stock', sa.Integer(), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('lifespan_km', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    op.create_index(op.f('ix_parts_name'), 'parts', ['name'], unique=False)
    op.create_index(op.f('ix_parts_part_number'), 'parts', ['part_number'], unique=False)
    op.create_index(op.f('ix_parts_serial_number'), 'parts', ['serial_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENTE_ATIVO', 'CLIENTE_DEMO', 'DRIVER', 'OPERATOR', 'MAINTENANCE', 'QUALITY', 'LOGISTICS', 'PCP', 'MANAGER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('notify_in_app', sa.Boolean(), nullable=False),
    sa.Column('notify_by_email', sa.Boolean(), nullable=False),
    sa.Column('notification_email', sa.String(length=100), nullable=True),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'organization_id', name='_user_employee_org_uc')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_reset_password_token'), 'users', ['reset_password_token'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('sap_resource_code', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'STOPPED', name='vehiclestatus'), nullable=False),
    sa.Column('current_km', sa.Integer(), nullable=False),
    sa.Column('current_engine_hours', sa.Float(), nullable=True),
    sa.Column('axle_configuration', sa.String(length=30), nullable=True),
    sa.Column('telemetry_device_id', sa.String(length=100), nullable=True),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_km', sa.Integer(), nullable=True),
    sa.Column('maintenance_notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', 'organization_id', name='_vehicle_identifier_org_uc'),
    sa.UniqueConstraint('license_plate', 'organization_id', name='_vehicle_license_org_uc'),
    sa.UniqueConstraint('telemetry_device_id', 'organization_id', name='_vehicle_telemetry_org_uc')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_telemetry_device_id'), 'vehicles', ['telemetry_device_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertlevel'), nullable=False),
    sa.Column('type', sa.Enum('GENERIC', 'SPEEDING', 'ROAD_HAZARD', 'MAINTENANCE', 'FRAUD', name='alerttype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('andon_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_andon_alerts_id'), 'andon_alerts', ['id'], unique=False)
    op.create_table('andon_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('sector', sa.Enum('MAINTENANCE', 'QUALITY', 'PCP', 'MANAGER', 'LOGISTICS', 'SECURITY', name='andonsector'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='andonstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_andon_calls_id'), 'andon_calls', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('CNH', 'CRLV', 'ANTT', 'ASO', 'SEGURO', 'OUTRO', name='documenttype'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('infraction_code', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'APPEALED', 'CANCELED', name='finestatus'), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_id'), 'fines', ['id'], unique=False)
    op.create_table('freight_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLAIMED', 'PENDING', 'IN_TRANSIT', 'DELIVERED', 'CANCELED', name='freightstatus'), nullable=False),
    sa.Column('scheduled_start_time', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end_time', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_orders_id'), 'freight_orders', ['id'], unique=False)
    op.create_table('fuel_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receipt_photo_url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'SUSPICIOUS', 'UNVERIFIED', 'PENDING', name='verificationstatus'), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('gas_station_name', sa.String(length=255), nullable=True),
    sa.Column('gas_station_latitude', sa.Float(), nullable=True),
    sa.Column('gas_station_longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'INTEGRATION', name='fuellogsource'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_logs_id'), 'fuel_logs', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_logs_provider_transaction_id'), 'fuel_logs', ['provider_transaction_id'], unique=True)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_identifier', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'EM_USO', 'FIM_DE_VIDA', 'EM_MANUTENCAO', name='inventoryitemstatus'), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('installed_on_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['installed_on_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'item_identifier', name='_part_item_identifier_uc')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_identifier'), 'inventory_items', ['item_identifier'], unique=False)
    op.create_index(op.f('ix_inventory_items_status'), 'inventory_items', ['status'], unique=False)
    op.create_table('location_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_history_id'), 'location_history', ['id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'PENDENTE', 'APROVADA', 'REJEITADA', 'EM_ANDAMENTO', 'CONCLUIDA', name='maintenancestatus'), nullable=False),
    sa.Column('category', sa.Enum('MECHANICAL', 'ELECTRICAL', 'HYDRAULIC', 'PNEUMATIC', 'BODYWORK', 'OTHER', name='maintenancecategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('manager_notes', sa.Text(), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mechanical', sa.Boolean(), nullable=True),
    sa.Column('is_electrical', sa.Boolean(), nullable=True),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(), nullable=True),
    sa.Column('supervisor', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_id'), 'maintenance_requests', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notification_type', sa.Enum('MAINTENANCE_DUE_DATE', 'MAINTENANCE_DUE_KM', 'DOCUMENT_EXPIRING', 'LOW_STOCK', 'TIRE_STATUS_BAD', 'ABNORMAL_FUEL_CONSUMPTION', 'COST_EXCEEDED', 'NEW_FINE_REGISTERED', 'FINE_PAYMENT_DUE', 'FREIGHT_ASSIGNED', 'FREIGHT_UPDATED', 'MAINTENANCE_REQUEST_NEW', 'MAINTENANCE_REQUEST_STATUS_UPDATE', 'MAINTENANCE_REQUEST_NEW_COMMENT', 'JOURNEY_STARTED', 'JOURNEY_ENDED', 'ACHIEVEMENT_UNLOCKED', 'LEADERBOARD_TOP3', name='notificationtype'), nullable=False),
    sa.Column('related_entity_type', sa.String(), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('related_vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['related_vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('production_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.String(length=50), nullable=False),
    sa.Column('op_number', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('operation_code', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('produced_qty', sa.Float(), nullable=True),
    sa.Column('scrap_qty', sa.Float(), nullable=True),
    sa.Column('target_qty', sa.Float(), nullable=True),
    sa.Column('appointment_type', sa.String(length=20), nullable=True),
    sa.Column('stop_reason', sa.String(length=255), nullable=True),
    sa.Column('sap_status', sa.String(length=20), nullable=True),
    sa.Column('sap_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_appointments_id'), 'production_appointments', ['id'], unique=False)
    op.create_index(op.f('ix_production_appointments_op_number'), 'production_appointments', ['op_number'], unique=False)
    op.create_index(op.f('ix_production_appointments_operator_id'), 'production_appointments', ['operator_id'], unique=False)
    op.create_table('production_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_produced', sa.Integer(), nullable=False),
    sa.Column('total_scrap', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('productive_seconds', sa.Integer(), nullable=False),
    sa.Column('unproductive_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_sessions_id'), 'production_sessions', ['id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='_user_achievement_uc')
    )
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('ENTRADA', 'SAIDA_USO', 'FIM_DE_VIDA', 'AJUSTE_INICIAL', 'INSTALACAO', 'DESCARTE', 'SAIDA_REPARO', name='transactiontype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('related_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('start_mileage', sa.Integer(), nullable=False),
    sa.Column('end_mileage', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trip_type', sa.String(length=50), nullable=False),
    sa.Column('implement_id', sa.Integer(), nullable=True),
    sa.Column('freight_order_id', sa.Integer(), nullable=True),
    sa.Column('trip_description', sa.String(), nullable=True),
    sa.Column('start_engine_hours', sa.Float(), nullable=True),
    sa.Column('end_engine_hours', sa.Float(), nullable=True),
    sa.Column('destination_address', sa.String(), nullable=True),
    sa.Column('destination_street', sa.String(length=255), nullable=True),
    sa.Column('destination_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('destination_city', sa.String(length=100), nullable=True),
    sa.Column('destination_state', sa.String(length=2), nullable=True),
    sa.Column('destination_cep', sa.String(length=9), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['freight_order_id'], ['freight_orders.id'], ),
    sa.ForeignKeyConstraint(['implement_id'], ['implements.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journeys_id'), 'journeys', ['id'], unique=False)
    op.create_table('maintenance_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_comments_id'), 'maintenance_comments', ['id'], unique=False)
    op.create_table('maintenance_service_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_service_items_id'), 'maintenance_service_items', ['id'], unique=False)
    op.create_table('production_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['production_sessions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_logs_id'), 'production_logs', ['id'], unique=False)
    op.create_table('production_time_slices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_productive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['production_sessions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_time_slices_id'), 'production_time_slices', ['id'], unique=False)
    op.create_table('stop_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freight_order_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PICKUP', 'DELIVERY', name='stoppointtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='stoppointstatus'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('cargo_description', sa.String(length=500), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['freight_order_id'], ['freight_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_points_id'), 'stop_points', ['id'], unique=False)
    op.create_table('vehicle_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cost_type', sa.Enum('MANUTENCAO', 'COMBUSTIVEL', 'PEDAGIO', 'SEGURO', 'PNEU', 'PECAS_COMPONENTES', 'MULTA', 'OUTROS', 'MANUTENCAO_CORRETIVA', 'MANUTENCAO_PREVENTIVA', 'ENERGIA_ELETRICA', 'PECAS_REPOSICAO', 'INSUMOS', 'SERVICOS_TERCEIROS', name='costtype'), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('fine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fine_id')
    )
    op.create_index(op.f('ix_vehicle_costs_id'), 'vehicle_costs', ['id'], unique=False)
    op.create_table('vehicle_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('inventory_transaction_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('installation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uninstallation_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_transaction_id')
    )
    op.create_index(op.f('ix_vehicle_components_id'), 'vehicle_components', ['id'], unique=False)
    op.create_table('vehicle_tires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('position_code', sa.String(length=20), nullable=False),
    sa.Column('install_km', sa.Integer(), nullable=False),
    sa.Column('removal_km', sa.Integer(), nullable=True),
    sa.Column('install_engine_hours', sa.Float(), nullable=True),
    sa.Column('removal_engine_hours', sa.Float(), nullable=True),
    sa.Column('km_run', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('installation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('removal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inventory_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_tires_id'), 'vehicle_tires', ['id'], unique=False)
    op.create_table('weather_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('affected_lat', sa.Float(), nullable=True),
    sa.Column('affected_lon', sa.Float(), nullable=True),
    sa.Column('affected_radius_km', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_events_id'), 'weather_events', ['id'], unique=False)
    op.create_table('maintenance_part_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('component_removed_id', sa.Integer(), nullable=True),
    sa.Column('component_installed_id', sa.Integer(), nullable=True),
    sa.Column('is_reverted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_installed_id'], ['vehicle_components.id'], ),
    sa.ForeignKeyConstraint(['component_removed_id'], ['vehicle_components.id'], ),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_part_changes_id'), 'maintenance_part_changes', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_part_changes_is_reverted'), 'maintenance_part_changes', ['is_reverted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_part_changes_is_reverted'), table_name='maintenance_part_changes')
    op.drop_index(op.f('ix_maintenance_part_changes_id'), table_name='maintenance_part_changes')
    op.drop_table('maintenance_part_changes')
    op.drop_index(op.f('ix_weather_events_id'), table_name='weather_events')
    op.drop_table('weather_events')
    op.drop_index(op.f('ix_vehicle_tires_id'), table_name='vehicle_tires')
    op.drop_table('vehicle_tires')
    op.drop_index(op.f('ix_vehicle_components_id'), table_name='vehicle_components')
    op.drop_table('vehicle_components')
    op.drop_index(op.f('ix_vehicle_costs_id'), table_name='vehicle_costs')
    op.drop_table('vehicle_costs')
    op.drop_index(op.f('ix_stop_points_id'), table_name='stop_points')
    op.drop_table('stop_points')
    op.drop_index(op.f('ix_production_time_slices_id'), table_name='production_time_slices')
    op.drop_table('production_time_slices')
    op.drop_index(op.f('ix_production_logs_id'), table_name='production_logs')
    op.drop_table('production_logs')
    op.drop_index(op.f('ix_maintenance_service_items_id'), table_name='maintenance_service_items')
    op.drop_table('maintenance_service_items')
    op.drop_index(op.f('ix_maintenance_comments_id'), table_name='maintenance_comments')
    op.drop_table('maintenance_comments')
    op.drop_index(op.f('ix_journeys_id'), table_name='journeys')
    op.drop_table('journeys')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_production_sessions_id'), table_name='production_sessions')
    op.drop_table('production_sessions')
    op.drop_index(op.f('ix_production_appointments_operator_id'), table_name='production_appointments')
    op.drop_index(op.f('ix_production_appointments_op_number'), table_name='production_appointments')
    op.drop_index(op.f('ix_production_appointments_id'), table_name='production_appointments')
    op.drop_table('production_appointments')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_maintenance_requests_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_location_history_id'), table_name='location_history')
    op.drop_table('location_history')
    op.drop_index(op.f('ix_inventory_items_status'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_identifier'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_fuel_logs_provider_transaction_id'), table_name='fuel_logs')
    op.drop_index(op.f('ix_fuel_logs_id'), table_name='fuel_logs')
    op.drop_table('fuel_logs')
    op.drop_index(op.f('ix_freight_orders_id'), table_name='freight_orders')
    op.drop_table('freight_orders')
    op.drop_index(op.f('ix_fines_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_andon_calls_id'), table_name='andon_calls')
    op.drop_table('andon_calls')
    op.drop_index(op.f('ix_andon_alerts_id'), table_name='andon_alerts')
    op.drop_table('andon_alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_vehicles_telemetry_device_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_reset_password_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parts_serial_number'), table_name='parts')
    op.drop_index(op.f('ix_parts_part_number'), table_name='parts')
    op.drop_index(op.f('ix_parts_name'), table_name='parts')
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_implements_id'), table_name='implements')
    op.drop_table('implements')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_demousage_resource_type'), table_name='demousage')
    op.drop_index(op.f('ix_demousage_organization_id'), table_name='demousage')
    op.drop_index(op.f('ix_demousage_id'), table_name='demousage')
    op.drop_table('demousage')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_vehicle_daily_metrics_id'), table_name='vehicle_daily_metrics')
    op.drop_index(op.f('ix_vehicle_daily_metrics_date'), table_name='vehicle_daily_metrics')
    op.drop_table('vehicle_daily_metrics')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_code'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_geofences_id'), table_name='geofences')
    op.drop_table('geofences')
    op.drop_index(op.f('ix_employee_daily_metrics_id'), table_name='employee_daily_metrics')
    op.drop_index(op.f('ix_employee_daily_metrics_date'), table_name='employee_daily_metrics')
    op.drop_table('employee_daily_metrics')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
