"""add_layout_coordinates

Revision ID: f1e94d82ca82
Revises: 062e22ff453f
Create Date: 2026-02-24 12:41:03.766756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e94d82ca82'
down_revision: Union[str, None] = '062e22ff453f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('layout_x', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('layout_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'layout_y')
    op.drop_column('vehicles', 'layout_x')
    # ### end Alembic commands ###
