server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redireciona a API para o Python
    location /api/ {
        proxy_pass http://192.168.0.5:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Redireciona o UPLOAD para o Python
    location /upload-photo {
        proxy_pass http://192.168.0.5:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Limite de 10MB para fotos (Essencial!)
        client_max_body_size 10M; 
    }
    
    # Libera a visualização das fotos já salvas
    location /static/ {
        proxy_pass http://192.168.0.5:8000;
    }
}